title = "Marcus Vechiato"
baseURL = "https://blog.vechiato.cc"
languageCode = "en-us"
theme = "clarity"
resourceDir = "../resources"

DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 8 
googleAnalytics = "G-6BYRELN45K"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Marcus Vechiato"
  #favicon = "/static/favicon.ico"
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "linkedin"
url = "https://linkedin.com/in/vechiato"

#[menu]
#  [[menu.main]]
#    identifier = "home"
#    name = "Home"
#    url = "/"
#    weight = 1
#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags/"
#    weight = 2

