title = "Marcus Vechiato"
baseURL = "https://blog.vechiato.cc"
languageCode = "en-us"
theme = "clarity"
resourceDir = "../resources"

DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 20 
googleAnalytics = "G-6BYRELN45K"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Marcus Vechiato"
  #favicon = "/static/favicon.ico"
  site_logo = ""
  numberOfTagsShown = 25
  description = "Discover insights on DevOps, SRE, Platform Engineering, and modern software development practices."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
    
  [params.share]
    twitter                  = true
    facebook                 = false
    linkedin                 = true

#  [params.social]
#    name = "linkedin"
#    url = "https://linkedin.com/in/vechiato"
  [[params.social]]
     url   = "https://linkedin.com/in/vechiato"
     icon  = "linkedin-in" # icon name without the 'fa-'
     icon_pack = "fab"

[taxonomies]
  tag = "tags"

#[menu]
#  [[menu.main]]
#    identifier = "home"
#    name = "Home"
#    url = "/"
#    weight = 1
#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags/"
#    weight = 2

